---
kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: restore-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            restore: true
            cache_key: '{{ checksum "go.mod" }}_{{ checksum "go.sum" }}_default'
            archive_format: gzip
            mount:
                - ./.go
        depends_on: [ clone ]
    -   name: get
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go get
        depends_on: [ restore-cache ]
    -   name: vet
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go vet
        depends_on: [ get ]
    -   name: build
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go version
            - go build -tags ""
            - go build -tags "scrape record"
        depends_on: [ get ]
    -   name: linter
        image: golangci/golangci-lint:latest
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - golangci-lint run --color always --build-tags ""
            - golangci-lint run --color always --build-tags "scrape record"
        depends_on: [ build ]
    -   name: rebuild-cache
        image: meltwater/drone-cache
        failure: ignore
        environment:
            AWS_ACCESS_KEY_ID:
                from_secret: aws_access_key_id
            AWS_SECRET_ACCESS_KEY:
                from_secret: aws_secret_access_key
            PLUGIN_PATH_STYLE: true
        settings:
            endpoint:
                from_secret: aws_endpoint
            region: ab-1
            bucket: drone-cache
            rebuild: true
            cache_key: '{{ checksum "go.mod" }}_{{ checksum "go.sum" }}_default'
            archive_format: gzip
            mount:
                - ./.go
        depends_on: [ get ]

trigger:
    branch:
        - master
        - drone

---
kind: signature
hmac: 41acbf30856919dee7443bc6457698f6d767dc55aae1288c7462b85642d4580f

...
