kind: pipeline
name: golang-v1.11
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: build
        image: golang:1.11
        commands:
            - go get
            - go build

trigger:
    branch:
        - master

---
kind: pipeline
name: golang-v1.13
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: build
        image: golang:1.13
        commands:
            - go get
            - go build

trigger:
    branch:
        - master
