kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: get
        image: golang:1.11
        volumes:
            - name: gopath
              path: /go
        environment:
            GOPATH: /go
        commands:
            - go get
    -   name: base build
        image: golang:1.11
        volumes:
            - name: gopath
              path: /go
        environment:
            GOPATH: /go
        commands:
            - go build -tags ""
    -   name: full build
        image: golang:1.11
        volumes:
            - name: gopath
              path: /go
        environment:
            GOPATH: /go
        commands:
            - go build -tags "scrape record"
    -   name: linter
        image: golangci/golangci-lint:v1.23.3
        volumes:
            - name: gopath
              path: /go
        environment:
            GOPATH: /go
        commands:
            - golangci-lint run --color always --build-tags "scrape record"
trigger:
    branch:
        - master
        - drone

volumes:
    - name: gopath
      temp: {}
