kind: pipeline
name: compliance
type: docker

steps:
    -   name: linter
        image: golangci/golangci-lint:v1.24.0-alpine
        commands:
            - golangci-lint run --color always

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: test
        image: golang:1.14-alpine
        environment:
            GO111MODULE: on
        commands:
            - CGO_ENABLED=0 go test ./... -v -coverprofile=coverage.out
            - go tool cover -func=coverage.out

---
kind: pipeline
name: docker
type: docker

steps:
    -   name: build
        image: plugins/docker
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/chihaya
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote
