---
kind: pipeline
name: compliance
type: docker

steps:
    -   name: vet
        image: golang:1.13
        environment:
            GO111MODULE: on
        commands:
            - go vet -tags "scrape record"
    -   name: linter
        image: golangci/golangci-lint:latest
        commands:
            - golangci-lint run --color always --build-tags "scrape record"

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: test
        image: golang:1.13
        environment:
            GO111MODULE: on
        commands:
            - go test ./... -tags "scrape record"

---
kind: pipeline
name: deploy
type: docker

steps:
    -   name: build
        image: golang:1.13
        environment:
            GO111MODULE: on
        commands:
            - go build -tags "scrape"
    -   name: upload
        image: plugins/s3
        settings:
            region: ab-1
            path_style: true
            bucket: deploy
            source: chihaya
            target: ${DRONE_REPO_NAME}
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint

trigger:
    branch:
        - master
    event:
        - push
    status:
        - success
    instance:
        include:
            - '*.animebytes.tv'

depends_on:
    - compliance
    - tests

---
kind: pipeline
name: artifacts
type: docker

steps:
    -   name: collect
        image: golang:1.13
        environment:
            GO111MODULE: on
        commands:
            - go mod vendor
    -   name: upload
        image: plugins/s3-cache
        settings:
            rebuild: true
            path: artifacts/${DRONE_REPO_NAME}/${DRONE_COMMIT}/
            mount:
                - vendor
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
    -   name: flush
        image: plugins/s3-cache
        settings:
            flush: true
            flush_age: 14
            flush_path: artifacts/${DRONE_REPO_NAME}/
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint

trigger:
    branch:
        - master
    event:
        - push
    status:
        - success
    instance:
        include:
            - '*.animebytes.tv'

depends_on:
    - compliance
    - tests
