---
kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: get
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go get
    -   name: vet
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go vet
        depends_on: [ get ]
    -   name: build
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go version
            - go build -tags ""
            - go build -tags "scrape record"
        depends_on: [ get ]
    -   name: linter
        image: golangci/golangci-lint:latest
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - golangci-lint run --color always --build-tags ""
            - golangci-lint run --color always --build-tags "scrape record"
        depends_on: [ build ]

trigger:
    branch:
        - master

---
kind: signature
hmac: b89e9100c6e596dc3075f1980b0cc0b0b12783c8d0a689398722b2285dc99ad7

...
