kind: pipeline
name: default
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: build
        image: golang:1.11
        volumes:
            - name: gopath
              path: /go
        environment:
            GOPATH: /go
        commands:
            - go get
            - go build -tags ""
            - go build -tags "scrape record"
    -   name: linter
        image: golangci/golangci-lint:latest
        volumes:
            - name: gopath
              path: /go
        environment:
            GOPATH: /go
        commands:
            - golangci-lint run --color always --build-tags "scrape record"

trigger:
    branch:
        - master
        - drone

volumes:
    - name: gopath
      temp: {}
