---
kind: pipeline
name: compliance
type: docker

steps:
    -   name: gofmt
        image: golangci/golangci-lint:v1.24.0-alpine
        commands:
            - golangci-lint run --color always --no-config --disable-all -E gofmt
        depends_on: [ clone ]
    -   name: linter
        image: golangci/golangci-lint:v1.24.0-alpine
        commands:
            - golangci-lint run --color always
        depends_on: [ clone ]

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: test
        image: golang:1.14-alpine
        environment:
            CGO_ENABLED: 0
            GO111MODULE: on
        commands:
            - go get -v -t -d ./...
            - go test ./... -v -coverprofile=coverage.out
    -   name: coverage
        image: golang:1.14-alpine
        commands:
            - go tool cover -func=coverage.out

---
kind: pipeline
name: docker
type: docker

platform:
    arch: amd64

steps:
    -   name: build
        image: plugins/docker
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
            build_args:
                - GIT_SHA=${DRONE_COMMIT_SHA:0:8}
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/chihaya
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote

depends_on:
    - compliance
    - tests
