kind: pipeline
name: compliance
type: docker

steps:
    -   name: linter
        image: golangci/golangci-lint:latest-alpine
        commands:
            - golangci-lint run --color always

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: test
        image: golang:1.13-alpine
        environment:
            GO111MODULE: on
        commands:
            - CGO_ENABLED=0 go test ./... -tags "scrape record" -coverprofile=coverage.out
            - go tool cover -func=coverage.out

trigger:
    event:
        exclude:
            - promote

---
kind: pipeline
name: docker
type: docker

steps:
    -   name: build
        image: plugins/docker
        privileged: true
        environment:
            DOCKER_REGISTRY:
                from_secret: docker_registry
        settings:
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            tags:
                - "${DRONE_DEPLOY_TO}"
        commands:
            - export PLUGIN_REPO=$DOCKER_REGISTRY/chihaya
            - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

trigger:
    event:
        - promote

---
kind: pipeline
name: artifacts
type: docker

steps:
    -   name: collect
        image: golang:1.13-alpine
        environment:
            GO111MODULE: on
        commands:
            - go mod vendor
    -   name: upload
        image: plugins/s3-cache
        settings:
            rebuild: true
            path: artifacts/${DRONE_REPO_NAME}/${DRONE_COMMIT}/
            mount:
                - vendor
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
        when:
            target:
                - production
    -   name: flush
        image: plugins/s3-cache
        settings:
            flush: true
            flush_age: 14
            flush_path: artifacts/${DRONE_REPO_NAME}/
            access_key:
                from_secret: aws_access_key_id
            secret_key:
                from_secret: aws_secret_access_key
            endpoint:
                from_secret: aws_endpoint
        when:
            target:
                - production

trigger:
    event:
        - promote
