linters:
    disable-all: true
    enable:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - structcheck
        - varcheck
        - ineffassign
        - deadcode
        - typecheck
        - megacheck
        - whitespace
        - wsl
        - maligned
        - goconst
        - unconvert
        - bodyclose
        - golint
        - gosec
        - interfacer
        - unconvert
        - goconst
        - dupl
        - misspell
        - lll
        - unparam
        - dogsled
        - prealloc
        - nolintlint
        - goerr113