run:
    timeout: 5m
    allow-parallel-runners: true

linters:
    disable-all: true
    enable:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - ineffassign
        - typecheck
        - megacheck
        - whitespace
        - wsl
        - goconst
        - unconvert
        - bodyclose
        - revive
        - gosec
        - unconvert
        - goconst
        - dupl
        - misspell
        - lll
        - unparam
        - dogsled
        - prealloc
        - nolintlint
        - goerr113

linters-settings:
    nolintlint:
        require-explanation: false
        require-specific: true
    wsl:
        strict-append: false
        force-err-cuddling: true

issues:
    exclude-rules:
        - path: (.+)_test\.go
          linters:
              - gosec
              - goconst
              - unparam