linters:
    disable-all: true
    enable:
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - structcheck
        - varcheck
        - ineffassign
        - deadcode
        - typecheck
        - megacheck
        - whitespace
        - wsl
        - goconst
        - unconvert
        - bodyclose
        - revive
        - gosec
        - unconvert
        - goconst
        - dupl
        - misspell
        - lll
        - unparam
        - dogsled
        - prealloc
        - nolintlint
        - goerr113

issues:
    exclude-rules:
        - path: _test\.go
          linters:
              - gosec