version: '2'
run:
    allow-parallel-runners: true
linters:
    default: none
    enable:
        - bodyclose
        - dogsled
        - err113
        - errcheck
        - goconst
        - gocyclo
        - gosec
        - govet
        - importas
        - ineffassign
        - lll
        - makezero
        - misspell
        - nolintlint
        - prealloc
        - predeclared
        - revive
        - staticcheck
        - unconvert
        - unparam
        - unused
        - whitespace
        - wsl_v5
    settings:
        gosec:
            excludes:
                - G115
        misspell:
            locale: US
        nolintlint:
            require-explanation: false
            require-specific: true
        wsl_v5:
            allow-first-in-block: true
            allow-whole-block: true
            branch-max-lines: 2
        revive:
            rules:
                - name: var-naming
                  disabled: true
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        rules:
            -   linters:
                    - goconst
                    - gosec
                    - unparam
                path: (.+)_test\.go
        paths:
            - third_party$
            - builtin$
            - examples$
formatters:
    enable:
        - gofmt
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
