name: testing

on:
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

concurrency:
    group: ${{ forge.workflow }}-${{ forge.ref }}
    cancel-in-progress: true

env:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOMAXPROCS: 2

jobs:
    suite:
        runs-on: ubuntu-24.04
        services:
            mariadb:
                image: mariadb:11.8
                env:
                    MYSQL_RANDOM_ROOT_PASSWORD: yes
                    MYSQL_DATABASE: chihaya_test
                    MYSQL_USER: drone
                    MYSQL_PASSWORD: w33lkn0wn
                    MYSQL_INITDB_SKIP_TZINFO: yes
        steps:
            -   name: Checkout
                uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            -   name: Set up Go
                uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
                with:
                    go-version-file: ./go.mod
            -   name: Prepare database schema
                env:
                    DEBIAN_FRONTEND: noninteractive
                run: mysql -udrone -pw33lkn0wn -hmariadb chihaya_test < database/schema.sql
            -   name: Run tests
                env:
                    DB_DSN: 'drone:w33lkn0wn@(mariadb)/chihaya_test?multiStatements=true'
                run: go test ./... -v -pgo=off -buildvcs=false -coverprofile=./coverage.out
            -   name: Get coverage
                run: go tool cover -func=coverage.out